/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface BcnButton {
        "variant": string;
    }
    interface BcnCard {
    }
    interface BcnDeck {
        "cards": any;
    }
    interface BcnLink {
    }
}
declare global {
    interface HTMLBcnButtonElement extends Components.BcnButton, HTMLStencilElement {
    }
    var HTMLBcnButtonElement: {
        prototype: HTMLBcnButtonElement;
        new (): HTMLBcnButtonElement;
    };
    interface HTMLBcnCardElement extends Components.BcnCard, HTMLStencilElement {
    }
    var HTMLBcnCardElement: {
        prototype: HTMLBcnCardElement;
        new (): HTMLBcnCardElement;
    };
    interface HTMLBcnDeckElement extends Components.BcnDeck, HTMLStencilElement {
    }
    var HTMLBcnDeckElement: {
        prototype: HTMLBcnDeckElement;
        new (): HTMLBcnDeckElement;
    };
    interface HTMLBcnLinkElement extends Components.BcnLink, HTMLStencilElement {
    }
    var HTMLBcnLinkElement: {
        prototype: HTMLBcnLinkElement;
        new (): HTMLBcnLinkElement;
    };
    interface HTMLElementTagNameMap {
        "bcn-button": HTMLBcnButtonElement;
        "bcn-card": HTMLBcnCardElement;
        "bcn-deck": HTMLBcnDeckElement;
        "bcn-link": HTMLBcnLinkElement;
    }
}
declare namespace LocalJSX {
    interface BcnButton {
        "variant"?: string;
    }
    interface BcnCard {
    }
    interface BcnDeck {
        "cards"?: any;
    }
    interface BcnLink {
    }
    interface IntrinsicElements {
        "bcn-button": BcnButton;
        "bcn-card": BcnCard;
        "bcn-deck": BcnDeck;
        "bcn-link": BcnLink;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "bcn-button": LocalJSX.BcnButton & JSXBase.HTMLAttributes<HTMLBcnButtonElement>;
            "bcn-card": LocalJSX.BcnCard & JSXBase.HTMLAttributes<HTMLBcnCardElement>;
            "bcn-deck": LocalJSX.BcnDeck & JSXBase.HTMLAttributes<HTMLBcnDeckElement>;
            "bcn-link": LocalJSX.BcnLink & JSXBase.HTMLAttributes<HTMLBcnLinkElement>;
        }
    }
}
